In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25],
                [26, 27, 28, 29, 30]])
print(arr)                

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [2]:
#extract frist row
print(arr[0])

[1 2 3 4 5]


In [3]:
#extract the last row
print(arr[5])

[26 27 28 29 30]


In [4]:
#extract the third column
print(arr[:, 2])


[ 3  8 13 18 23 28]


In [5]:
#extract frist three rows
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
#extract last three rows
print(arr[-3:])

[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
#extract frist two colunm 
print(arr[:, :2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]
 [26 27]]


In [8]:
#extract last two colunm 
print(arr[:, -2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]


In [9]:
#Extract the subarray containing rows 1 to 3 and columns 2 to 4. 
print(arr[1:4, 2:5])

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [11]:
#Extract all rows from index 2 onward. 
print(arr[2:, :])

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [12]:
 
#Extract all columns from index 3 onward. 
print(arr[:, 3:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]


In [ ]:
#Extract every second row. 
print(arr[::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [14]:
#	Extract every second column. 
print(arr[:, ::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]]


In [15]:
#Extract the bottom-right 3×2 block.
print(arr[-3:, -2:])

[[19 20]
 [24 25]
 [29 30]]


In [16]:
#Extract the top-left 4×3 block
print(arr[:4, :3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [17]:
#Reverse the order of rows
print(arr[::-1])

[[26 27 28 29 30]
 [21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [18]:
#Reverse the order of columns
print(arr[:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]
 [30 29 28 27 26]]


In [19]:
#Reverse both rows and columns. 
print(arr[::-1, ::-1])

[[30 29 28 27 26]
 [25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [20]:
#Extract the middle 2×3 block. 
print(arr[2:4, 1:4])

[[12 13 14]
 [17 18 19]]


In [21]:
#Extract the first and last rows only. 
print(arr[[0, -1]])

[[ 1  2  3  4  5]
 [26 27 28 29 30]]


In [22]:
#Extract the first and last columns only. 
print(arr[:, [0, -1]])

[[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]
 [26 30]]


In [ ]:
#Extract all odd-indexed rows. 
print(arr[1::2])

In [ ]:
#Extract all even-indexed columns. 
print(arr[:, 0::2])

In [ ]:
#Extract the element at row index 4 and column index 2.
print(arr[4, 2]) 

In [ ]:
#Extract the entire row containing the value 18. 
print(arr[arr == 18])
print(arr[3])

In [ ]:
#Extract the entire column containing the value 14. 
print(arr[:, 3])

In [ ]:
#Extract the four corner elements. 
print(arr[[0, 0, -1, -1], [0, -1, 0, -1]])

In [ ]:
#Extract the central column only.
print(arr[:, 2]) 

In [ ]:
#Extract rows 1 to 4 and every second column. 
print(arr[1:5, ::2])

In [ ]:
#Extract every row but only columns with indices 1, 2, and 3. 
print(arr[:, 1:4])

In [ ]:
#Extract a 2×2 block from the center of the array.
print(arr[2:4, 2:4])